# Generated by Django 5.0.6 on 2024-06-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_name_review_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='feedback',
            new_name='review_text',
        ),
    ]
